[phases.setup]
nixPkgs = [
  "nodejs",
  "python3",
  "python3Packages.pip",
  "python3Packages.numpy",
  "python3Packages.scikit-learn",
  "python3Packages.flask",
  "python3Packages.joblib",
  "python3Packages.gunicorn"
]

[phases.install]
cmds = [
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && CI=false npm run build"
]

[start]
cmd = "cd backend && gunicorn app:app -b 0.0.0.0:${PORT:-5000}"