[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip"]

[phases.build]
cmds = [
  "cd frontend && npm install && CI=false npm run build",
  "cd backend && pip3 install --break-system-packages -r requirements.txt"
]

[start]
cmd = "cd backend && python3 app.py"